-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE DeriveTraversable #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE PatternSynonyms #-}

-- | The abstract syntax of language Flan.

module Flan.Abs where

import Prelude (Integer, String)
import qualified Prelude as C
  ( Eq, Ord, Show, Read
  , Functor, Foldable, Traversable
  , Int, Maybe(..)
  )
import qualified Data.String

type Program = Program' BNFC'Position
data Program' a = AProgram a (Term' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Binding = Binding' BNFC'Position
data Binding' a = LetBinding a (TypedPattern' a) (Term' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Term = Term' BNFC'Position
data Term' a
    = Let a [Binding' a] (Term' a)
    | Lam a (TypedPattern' a) (Term' a)
    | App a (Term' a) (Term' a)
    | If a (Term' a) (Term' a) (Term' a)
    | Pair a (Term' a) (Term' a)
    | Var a VarIdent
    | ConstTrue a
    | ConstFalse a
    | ConstInt a Integer
    | ConstStr a String
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type TypedPattern = TypedPattern' BNFC'Position
data TypedPattern' a
    = ATypedPattern a (Pattern' a) (FlanType' a)
    | UntypedPattern a (Pattern' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Pattern = Pattern' BNFC'Position
data Pattern' a
    = PatternVar a VarIdent
    | PatternPair a (Pattern' a) (Pattern' a)
    | PatternWildcard a
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type FlanType = FlanType' BNFC'Position
data FlanType' a
    = ValType a VarIdent
    | FunType a (FlanType' a) (FlanType' a)
    | PairType a (FlanType' a) (FlanType' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

newtype VarIdent = VarIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

-- | Start position (line, column) of something.

type BNFC'Position = C.Maybe (C.Int, C.Int)

pattern BNFC'NoPosition :: BNFC'Position
pattern BNFC'NoPosition = C.Nothing

pattern BNFC'Position :: C.Int -> C.Int -> BNFC'Position
pattern BNFC'Position line col = C.Just (line, col)

-- | Get the start position of something.

class HasPosition a where
  hasPosition :: a -> BNFC'Position

instance HasPosition Program where
  hasPosition = \case
    AProgram p _ -> p

instance HasPosition Binding where
  hasPosition = \case
    LetBinding p _ _ -> p

instance HasPosition Term where
  hasPosition = \case
    Let p _ _ -> p
    Lam p _ _ -> p
    App p _ _ -> p
    If p _ _ _ -> p
    Pair p _ _ -> p
    Var p _ -> p
    ConstTrue p -> p
    ConstFalse p -> p
    ConstInt p _ -> p
    ConstStr p _ -> p

instance HasPosition TypedPattern where
  hasPosition = \case
    ATypedPattern p _ _ -> p
    UntypedPattern p _ -> p

instance HasPosition Pattern where
  hasPosition = \case
    PatternVar p _ -> p
    PatternPair p _ _ -> p
    PatternWildcard p -> p

instance HasPosition FlanType where
  hasPosition = \case
    ValType p _ -> p
    FunType p _ _ -> p
    PairType p _ _ -> p

