-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE CPP #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE LambdaCase #-}
#if __GLASGOW_HASKELL__ <= 708
{-# LANGUAGE OverlappingInstances #-}
#endif

-- | Pretty-printer for Flan.

module Flan.Print where

import Prelude
  ( ($), (.)
  , Bool(..), (==), (<)
  , Int, Integer, Double, (+), (-), (*)
  , String, (++)
  , ShowS, showChar, showString
  , all, elem, foldr, id, map, null, replicate, shows, span
  )
import Data.Char ( Char, isSpace )
import qualified Flan.Abs

-- | The top-level printing method.

printTree :: Print a => a -> String
printTree = render . prt 0

type Doc = [ShowS] -> [ShowS]

doc :: ShowS -> Doc
doc = (:)

render :: Doc -> String
render d = rend 0 False (map ($ "") $ d []) ""
  where
  rend
    :: Int        -- ^ Indentation level.
    -> Bool       -- ^ Pending indentation to be output before next character?
    -> [String]
    -> ShowS
  rend i p = \case
      "["      :ts -> char '[' . rend i False ts
      "("      :ts -> char '(' . rend i False ts
      "{"      :ts -> onNewLine i     p . showChar   '{'  . new (i+1) ts
      "}" : ";":ts -> onNewLine (i-1) p . showString "};" . new (i-1) ts
      "}"      :ts -> onNewLine (i-1) p . showChar   '}'  . new (i-1) ts
      [";"]        -> char ';'
      ";"      :ts -> char ';' . new i ts
      t  : ts@(s:_) | closingOrPunctuation s
                   -> pending . showString t . rend i False ts
      t        :ts -> pending . space t      . rend i False ts
      []           -> id
    where
    -- Output character after pending indentation.
    char :: Char -> ShowS
    char c = pending . showChar c

    -- Output pending indentation.
    pending :: ShowS
    pending = if p then indent i else id

  -- Indentation (spaces) for given indentation level.
  indent :: Int -> ShowS
  indent i = replicateS (2*i) (showChar ' ')

  -- Continue rendering in new line with new indentation.
  new :: Int -> [String] -> ShowS
  new j ts = showChar '\n' . rend j True ts

  -- Make sure we are on a fresh line.
  onNewLine :: Int -> Bool -> ShowS
  onNewLine i p = (if p then id else showChar '\n') . indent i

  -- Separate given string from following text by a space (if needed).
  space :: String -> ShowS
  space t s =
    case (all isSpace t, null spc, null rest) of
      (True , _   , True ) -> []             -- remove trailing space
      (False, _   , True ) -> t              -- remove trailing space
      (False, True, False) -> t ++ ' ' : s   -- add space if none
      _                    -> t ++ s
    where
      (spc, rest) = span isSpace s

  closingOrPunctuation :: String -> Bool
  closingOrPunctuation [c] = c `elem` closerOrPunct
  closingOrPunctuation _   = False

  closerOrPunct :: String
  closerOrPunct = ")],;"

parenth :: Doc -> Doc
parenth ss = doc (showChar '(') . ss . doc (showChar ')')

concatS :: [ShowS] -> ShowS
concatS = foldr (.) id

concatD :: [Doc] -> Doc
concatD = foldr (.) id

replicateS :: Int -> ShowS -> ShowS
replicateS n f = concatS (replicate n f)

-- | The printer class does the job.

class Print a where
  prt :: Int -> a -> Doc

instance {-# OVERLAPPABLE #-} Print a => Print [a] where
  prt i = concatD . map (prt i)

instance Print Char where
  prt _ c = doc (showChar '\'' . mkEsc '\'' c . showChar '\'')

instance Print String where
  prt _ = printString

printString :: String -> Doc
printString s = doc (showChar '"' . concatS (map (mkEsc '"') s) . showChar '"')

mkEsc :: Char -> Char -> ShowS
mkEsc q = \case
  s | s == q -> showChar '\\' . showChar s
  '\\' -> showString "\\\\"
  '\n' -> showString "\\n"
  '\t' -> showString "\\t"
  s -> showChar s

prPrec :: Int -> Int -> Doc -> Doc
prPrec i j = if j < i then parenth else id

instance Print Integer where
  prt _ x = doc (shows x)

instance Print Double where
  prt _ x = doc (shows x)

instance Print Flan.Abs.VarIdent where
  prt _ (Flan.Abs.VarIdent i) = doc $ showString i
instance Print (Flan.Abs.Program' a) where
  prt i = \case
    Flan.Abs.AProgram _ term -> prPrec i 0 (concatD [prt 0 term])

instance Print (Flan.Abs.Binding' a) where
  prt i = \case
    Flan.Abs.LetBinding _ typedpattern leteq term -> prPrec i 0 (concatD [doc (showString "|"), prt 0 typedpattern, prt 0 leteq, prt 0 term])

instance Print (Flan.Abs.LetEq' a) where
  prt i = \case
    Flan.Abs.ALetEq _ -> prPrec i 0 (concatD [doc (showString "=")])

instance Print [Flan.Abs.Binding' a] where
  prt _ [] = concatD []
  prt _ (x:xs) = concatD [prt 0 x, prt 0 xs]

instance Print (Flan.Abs.Term' a) where
  prt i = \case
    Flan.Abs.Let _ bindings letin term -> prPrec i 0 (concatD [prt 0 bindings, prt 0 letin, prt 0 term])
    Flan.Abs.Lam _ typedpattern lamarrow term -> prPrec i 0 (concatD [doc (showString "/"), prt 0 typedpattern, prt 0 lamarrow, prt 0 term])
    Flan.Abs.App _ term1 term2 -> prPrec i 1 (concatD [prt 1 term1, prt 2 term2])
    Flan.Abs.If _ term1 thenkw term2 elsekw term3 -> prPrec i 0 (concatD [doc (showString "if"), prt 0 term1, prt 0 thenkw, prt 0 term2, prt 0 elsekw, prt 0 term3])
    Flan.Abs.Pair _ term1 paircomma term2 closingbracket -> prPrec i 0 (concatD [doc (showString "["), prt 0 term1, prt 0 paircomma, prt 0 term2, prt 0 closingbracket])
    Flan.Abs.Var _ varident -> prPrec i 3 (concatD [prt 0 varident])
    Flan.Abs.ConstTrue _ -> prPrec i 3 (concatD [doc (showString "True")])
    Flan.Abs.ConstFalse _ -> prPrec i 3 (concatD [doc (showString "False")])
    Flan.Abs.ConstInt _ n -> prPrec i 3 (concatD [prt 0 n])
    Flan.Abs.ConstStr _ str -> prPrec i 3 (concatD [printString str])

instance Print (Flan.Abs.LetIn' a) where
  prt i = \case
    Flan.Abs.ALetIn _ -> prPrec i 0 (concatD [doc (showString "\\")])

instance Print (Flan.Abs.LamArrow' a) where
  prt i = \case
    Flan.Abs.ALamArrow _ -> prPrec i 0 (concatD [doc (showString "=>")])

instance Print (Flan.Abs.ThenKW' a) where
  prt i = \case
    Flan.Abs.IfThenKW _ -> prPrec i 0 (concatD [doc (showString "then")])

instance Print (Flan.Abs.ElseKW' a) where
  prt i = \case
    Flan.Abs.IfElseKW _ -> prPrec i 0 (concatD [doc (showString "else")])

instance Print (Flan.Abs.PairComma' a) where
  prt i = \case
    Flan.Abs.APairComma _ -> prPrec i 0 (concatD [doc (showString ",")])

instance Print (Flan.Abs.ClosingBracket' a) where
  prt i = \case
    Flan.Abs.PairClosingBracket _ -> prPrec i 0 (concatD [doc (showString "]")])

instance Print (Flan.Abs.TypedPattern' a) where
  prt i = \case
    Flan.Abs.ATypedPattern _ pattern_ typedpatterncolon flantype -> prPrec i 0 (concatD [prt 0 pattern_, prt 0 typedpatterncolon, prt 0 flantype])
    Flan.Abs.UntypedPattern _ pattern_ -> prPrec i 0 (concatD [prt 0 pattern_])

instance Print (Flan.Abs.TypedPatternColon' a) where
  prt i = \case
    Flan.Abs.ATypedPatternColon _ -> prPrec i 0 (concatD [doc (showString ":")])

instance Print (Flan.Abs.Pattern' a) where
  prt i = \case
    Flan.Abs.PatternVar _ varident -> prPrec i 0 (concatD [prt 0 varident])
    Flan.Abs.PatternPair _ pattern_1 patternpaircomma pattern_2 patternpairclosingbracket -> prPrec i 0 (concatD [doc (showString "["), prt 0 pattern_1, prt 0 patternpaircomma, prt 0 pattern_2, prt 0 patternpairclosingbracket])
    Flan.Abs.PatternWildcard _ -> prPrec i 0 (concatD [doc (showString "_")])

instance Print (Flan.Abs.PatternPairComma' a) where
  prt i = \case
    Flan.Abs.APatternPairComma _ -> prPrec i 0 (concatD [doc (showString ",")])

instance Print (Flan.Abs.PatternPairClosingBracket' a) where
  prt i = \case
    Flan.Abs.APatternPairClosingBracket _ -> prPrec i 0 (concatD [doc (showString "]")])

instance Print (Flan.Abs.FlanType' a) where
  prt i = \case
    Flan.Abs.AnyType _ -> prPrec i 2 (concatD [doc (showString "_")])
    Flan.Abs.ValType _ varident -> prPrec i 2 (concatD [prt 0 varident])
    Flan.Abs.FunType _ flantype1 funtypearrow flantype2 -> prPrec i 1 (concatD [prt 1 flantype1, prt 0 funtypearrow, prt 0 flantype2])
    Flan.Abs.PairType _ flantype1 pairtypecomma flantype2 pairtypeclosingbracket -> prPrec i 1 (concatD [doc (showString "["), prt 0 flantype1, prt 0 pairtypecomma, prt 0 flantype2, prt 0 pairtypeclosingbracket])

instance Print (Flan.Abs.FunTypeArrow' a) where
  prt i = \case
    Flan.Abs.AFunTypeArrow _ -> prPrec i 0 (concatD [doc (showString "->")])

instance Print (Flan.Abs.PairTypeComma' a) where
  prt i = \case
    Flan.Abs.APairTypeComma _ -> prPrec i 0 (concatD [doc (showString ",")])

instance Print (Flan.Abs.PairTypeClosingBracket' a) where
  prt i = \case
    Flan.Abs.APairTypeClosingBracket _ -> prPrec i 0 (concatD [doc (showString "]")])
