-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Flan.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Flan.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transVarIdent :: Flan.Abs.VarIdent -> Result
transVarIdent x = case x of
  Flan.Abs.VarIdent string -> failure x

transProgram :: Show a => Flan.Abs.Program' a -> Result
transProgram x = case x of
  Flan.Abs.AProgram _ term -> failure x

transBinding :: Show a => Flan.Abs.Binding' a -> Result
transBinding x = case x of
  Flan.Abs.LetBinding _ typedpattern term -> failure x

transTerm :: Show a => Flan.Abs.Term' a -> Result
transTerm x = case x of
  Flan.Abs.Let _ bindings term -> failure x
  Flan.Abs.Lam _ typedpattern term -> failure x
  Flan.Abs.App _ term1 term2 -> failure x
  Flan.Abs.If _ term1 term2 term3 -> failure x
  Flan.Abs.Pair _ term1 term2 -> failure x
  Flan.Abs.Var _ varident -> failure x
  Flan.Abs.ConstTrue _ -> failure x
  Flan.Abs.ConstFalse _ -> failure x
  Flan.Abs.ConstInt _ integer -> failure x
  Flan.Abs.ConstStr _ string -> failure x

transTypedPattern :: Show a => Flan.Abs.TypedPattern' a -> Result
transTypedPattern x = case x of
  Flan.Abs.ATypedPattern _ pattern_ flantype -> failure x
  Flan.Abs.UntypedPattern _ pattern_ -> failure x

transPattern :: Show a => Flan.Abs.Pattern' a -> Result
transPattern x = case x of
  Flan.Abs.PatternVar _ varident -> failure x
  Flan.Abs.PatternPair _ pattern_1 pattern_2 -> failure x
  Flan.Abs.PatternWildcard _ -> failure x

transFlanType :: Show a => Flan.Abs.FlanType' a -> Result
transFlanType x = case x of
  Flan.Abs.ValType _ varident -> failure x
  Flan.Abs.FunType _ flantype1 flantype2 -> failure x
  Flan.Abs.PairType _ flantype1 flantype2 -> failure x
