name:                free-foil-ls
version:             0.1.0.0
github:              "xdkomel/free-foil-ls"
license:             BSD-3-Clause
author:              "Kamil Foatov"
maintainer:          "xdkomel@gmail.com"
copyright:           "2025 Kamil Foatov"

extra-source-files:
- README.md
- CHANGELOG.md

description: Please see the README on GitHub at <https://github.com/githubuser/free-foil-ls#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -fno-defer-type-errors

library:
  source-dirs: src
  exposed-modules:
  - AgnosticLanguageServer
  other-modules:
  - AgnosticLanguageServer.AST
  - AgnosticLanguageServer.Cache
  - AgnosticLanguageServer.Classes
  - AgnosticLanguageServer.Common
  - AgnosticLanguageServer.Types
  - AgnosticLanguageServer.Handlers.Definition
  - AgnosticLanguageServer.Handlers.Diagnostics
  - AgnosticLanguageServer.Handlers.Hover
  - AgnosticLanguageServer.Handlers.Rename
  - AgnosticLanguageServer.Handlers.SemanticTokens
  - AgnosticLanguageServer.Handlers.Sync
  dependencies:
  - lsp
  - lsp-types
  - text
  - stm >=2.5.0.0
  - containers >=0.7
  - mtl >=2.2.2
  - Glob >=0.9.3
  - lens >=4.17
  - free-foil
  ghc-options:
  - -fno-defer-type-errors
