-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Lampi.Skel where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Lampi.Abs

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transVarIdent :: Lampi.Abs.VarIdent -> Result
transVarIdent x = case x of
  Lampi.Abs.VarIdent string -> failure x

transProgram :: Show a => Lampi.Abs.Program' a -> Result
transProgram x = case x of
  Lampi.Abs.AProgram _ commands -> failure x

transCommand :: Show a => Lampi.Abs.Command' a -> Result
transCommand x = case x of
  Lampi.Abs.CommandCheck _ term1 term2 -> failure x
  Lampi.Abs.CommandCompute _ term1 term2 -> failure x

transTerm :: Show a => Lampi.Abs.Term' a -> Result
transTerm x = case x of
  Lampi.Abs.Var _ varident -> failure x
  Lampi.Abs.Pi _ pattern_ term scopedterm -> failure x
  Lampi.Abs.Lam _ pattern_ scopedterm -> failure x
  Lampi.Abs.App _ term1 term2 -> failure x
  Lampi.Abs.Product _ term1 term2 -> failure x
  Lampi.Abs.Pair _ term1 term2 -> failure x
  Lampi.Abs.First _ term -> failure x
  Lampi.Abs.Second _ term -> failure x
  Lampi.Abs.Universe _ -> failure x

transScopedTerm :: Show a => Lampi.Abs.ScopedTerm' a -> Result
transScopedTerm x = case x of
  Lampi.Abs.AScopedTerm _ term -> failure x

transPattern :: Show a => Lampi.Abs.Pattern' a -> Result
transPattern x = case x of
  Lampi.Abs.PatternWildcard _ -> failure x
  Lampi.Abs.PatternVar _ varident -> failure x
  Lampi.Abs.PatternPair _ pattern_1 pattern_2 -> failure x
