-- File generated by the BNF Converter (bnfc 2.9.5).

{-# LANGUAGE DeriveTraversable #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE PatternSynonyms #-}

-- | The abstract syntax of language Hsls.

module Hsls.AbsHsls where

import Prelude (Double, Integer, String)
import qualified Prelude as C
  ( Eq, Ord, Show, Read
  , Functor, Foldable, Traversable
  , Int, Maybe(..)
  )
import qualified Data.String

type Program = Program' BNFC'Position
data Program' a = AProgram a [Decl' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Decl = Decl' BNFC'Position
data Decl' a = DeclFun a (Name' a) [Name' a] [Statement' a]
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Statement = Statement' BNFC'Position
data Statement' a
    = ReturnStatement a (Expr' a)
    | AssignStatement a (Name' a) (Expr' a)
    | ExprStatement a (Expr' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Expr = Expr' BNFC'Position
data Expr' a
    = FnCall a (Name' a) [Expr' a]
    | ConstTrue a
    | ConstFalse a
    | ConstInt a Integer
    | ConstDouble a Double
    | Var a (Name' a)
    | Sum a (Expr' a) (Expr' a)
    | Sub a (Expr' a) (Expr' a)
    | Mul a (Expr' a) (Expr' a)
    | Div a (Expr' a) (Expr' a)
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

type Name = Name' BNFC'Position
data Name' a = HslsName a LangIdent
  deriving (C.Eq, C.Ord, C.Show, C.Read, C.Functor, C.Foldable, C.Traversable)

newtype LangIdent = LangIdent String
  deriving (C.Eq, C.Ord, C.Show, C.Read, Data.String.IsString)

-- | Start position (line, column) of something.

type BNFC'Position = C.Maybe (C.Int, C.Int)

pattern BNFC'NoPosition :: BNFC'Position
pattern BNFC'NoPosition = C.Nothing

pattern BNFC'Position :: C.Int -> C.Int -> BNFC'Position
pattern BNFC'Position line col = C.Just (line, col)

-- | Get the start position of something.

class HasPosition a where
  hasPosition :: a -> BNFC'Position

instance HasPosition Program where
  hasPosition = \case
    AProgram p _ -> p

instance HasPosition Decl where
  hasPosition = \case
    DeclFun p _ _ _ -> p

instance HasPosition Statement where
  hasPosition = \case
    ReturnStatement p _ -> p
    AssignStatement p _ _ -> p
    ExprStatement p _ -> p

instance HasPosition Expr where
  hasPosition = \case
    FnCall p _ _ -> p
    ConstTrue p -> p
    ConstFalse p -> p
    ConstInt p _ -> p
    ConstDouble p _ -> p
    Var p _ -> p
    Sum p _ _ -> p
    Sub p _ _ -> p
    Mul p _ _ -> p
    Div p _ _ -> p

instance HasPosition Name where
  hasPosition = \case
    HslsName p _ -> p

