-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Hsls.SkelHsls where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Hsls.AbsHsls

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transLangIdent :: Hsls.AbsHsls.LangIdent -> Result
transLangIdent x = case x of
  Hsls.AbsHsls.LangIdent string -> failure x

transProgram :: Show a => Hsls.AbsHsls.Program' a -> Result
transProgram x = case x of
  Hsls.AbsHsls.AProgram _ decls -> failure x

transDecl :: Show a => Hsls.AbsHsls.Decl' a -> Result
transDecl x = case x of
  Hsls.AbsHsls.DeclFun _ name names statements -> failure x

transStatement :: Show a => Hsls.AbsHsls.Statement' a -> Result
transStatement x = case x of
  Hsls.AbsHsls.ReturnStatement _ expr -> failure x
  Hsls.AbsHsls.AssignStatement _ name expr -> failure x
  Hsls.AbsHsls.ExprStatement _ expr -> failure x

transExpr :: Show a => Hsls.AbsHsls.Expr' a -> Result
transExpr x = case x of
  Hsls.AbsHsls.FnCall _ name exprs -> failure x
  Hsls.AbsHsls.ConstTrue _ -> failure x
  Hsls.AbsHsls.ConstFalse _ -> failure x
  Hsls.AbsHsls.ConstInt _ integer -> failure x
  Hsls.AbsHsls.ConstDouble _ double -> failure x
  Hsls.AbsHsls.Var _ name -> failure x
  Hsls.AbsHsls.Sum _ expr1 expr2 -> failure x
  Hsls.AbsHsls.Sub _ expr1 expr2 -> failure x
  Hsls.AbsHsls.Mul _ expr1 expr2 -> failure x
  Hsls.AbsHsls.Div _ expr1 expr2 -> failure x

transName :: Show a => Hsls.AbsHsls.Name' a -> Result
transName x = case x of
  Hsls.AbsHsls.HslsName _ langident -> failure x
