-- File generated by the BNF Converter (bnfc 2.9.5).

-- Templates for pattern matching on abstract syntax

{-# OPTIONS_GHC -fno-warn-unused-matches #-}

module Lampi.SkelLampi where

import Prelude (($), Either(..), String, (++), Show, show)
import qualified Lampi.AbsLampi

type Err = Either String
type Result = Err String

failure :: Show a => a -> Result
failure x = Left $ "Undefined case: " ++ show x

transVarIdent :: Lampi.AbsLampi.VarIdent -> Result
transVarIdent x = case x of
  Lampi.AbsLampi.VarIdent string -> failure x

transProgram :: Show a => Lampi.AbsLampi.Program' a -> Result
transProgram x = case x of
  Lampi.AbsLampi.AProgram _ commands -> failure x

transCommand :: Show a => Lampi.AbsLampi.Command' a -> Result
transCommand x = case x of
  Lampi.AbsLampi.CommandCheck _ term1 term2 -> failure x
  Lampi.AbsLampi.CommandCompute _ term1 term2 -> failure x

transTerm :: Show a => Lampi.AbsLampi.Term' a -> Result
transTerm x = case x of
  Lampi.AbsLampi.Var _ varident -> failure x
  Lampi.AbsLampi.Pi _ pattern_ term scopedterm -> failure x
  Lampi.AbsLampi.Lam _ pattern_ scopedterm -> failure x
  Lampi.AbsLampi.App _ term1 term2 -> failure x
  Lampi.AbsLampi.Product _ term1 term2 -> failure x
  Lampi.AbsLampi.Pair _ term1 term2 -> failure x
  Lampi.AbsLampi.First _ term -> failure x
  Lampi.AbsLampi.Second _ term -> failure x
  Lampi.AbsLampi.Universe _ -> failure x

transScopedTerm :: Show a => Lampi.AbsLampi.ScopedTerm' a -> Result
transScopedTerm x = case x of
  Lampi.AbsLampi.AScopedTerm _ term -> failure x

transPattern :: Show a => Lampi.AbsLampi.Pattern' a -> Result
transPattern x = case x of
  Lampi.AbsLampi.PatternWildcard _ -> failure x
  Lampi.AbsLampi.PatternVar _ varident -> failure x
  Lampi.AbsLampi.PatternPair _ pattern_1 pattern_2 -> failure x
